version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels: ["dependencies"]
    reviewers: ["@your-org/maintainers"]
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels: ["ci"]
    reviewers: ["@your-org/maintainers"]